### PR TITLE
Fix cleanup when data contains an array

### PR DESCRIPTION
**Pull request by noxxious**
Please pull the change, this fixes a break when the web response is an array. You can run the updated tests before the fix to see them break.
This also affects the seneca-jsonrest-api as fetching the list does not work currently.

When playing with this I got some errors regarding cannon method in entities, as these are part of *private$* that get's removed.

### CODE REVIEW

**Comment by david-cahill** [comment]
+1

**Comment by thekemkid** [comment]
+1

**Comment by faceleg** [comment]
@rjrodger bump

**Comment by mcdonnelldean** [comment]
@geek Can you have a quick eyeball, this looks ok to me.

**Pull request merged**
