### PR TITLE
Don't delete headers when result is an array.

### PR DESCRIPTION
**Pull request by wprl**
Fixes not being able to set headers for array results.  They will be `_.clone`d which causes them to lose metadata like `http$`.  

Semi-related to: https://github.com/rjrodger/seneca-web/pull/16 (this PR augments the tests from there).

### CODE REVIEW

**Comment by mcdonnelldean** [comment]
@geek This one too

**Comment by geek** [comment]
LGTM, please update as it can't be merged @wprl

**Comment by wprl** [comment]
OK I’ll try to take a look by the end of the week.

**Comment by wprl** [comment]
Merge conflicts resolved and tests passing!

**Pull request merged**
